// config
switch (CF_ENDPOINT_MODE) {
  case 'PROD':
    AOAS_API = CF_AOAS_API_PROD;
    ASTS_API = CF_ASTS_API_PROD;
    VIG_API = CF_VIG_API_PROD;
    FOTA_API = CF_FOTA_API_PROD;
    APPCLIENTID = CF_APPCLIENTID_PROD;
    break;
  case 'QAT':
    AOAS_API = CF_AOAS_QAT_API;
    ASTS_API = CF_ASTS_API_QAT;
    VIG_API = CF_VIG_API_QAT;
    FOTA_API = CF_FOTA_API_QAT;
    APPCLIENTID = CF_APPCLIENTID_QAT;
    break;
  case 'DEV2':
    AOAS_API = CF_AOAS_API_DEV2;
    ASTS_API = CF_ASTS_API_DEV2;
    VIG_API = CF_VIG_API_DEV2;
    FOTA_API = CF_FOTA_API_DEV2;
    APPCLIENTID = CF_APPCLIENTID_DEV2;
    break;
  default:
    AOAS_API = CF_AOAS_API_PROD;
    ASTS_API = CF_ASTS_API_PROD;
    VIG_API = CF_VIG_API_PROD;
    FOTA_API = CF_FOTA_API_PROD;
    APPCLIENTID = CF_APPCLIENTID_PROD;
}
